import { Tees } from './tee_type.model';

export interface Course{
  id: number,
  status: string,
  membership_type: string,
  practice_area_id: number,
  measurement_type: string,
  media_id: number,
  hole_count: number,
  local_rank: number,
  local_max_rank: number,
  global_rank: number,
  name: string,
  addr_1: string,
  city: string,
  state_or_province: string,
  country: string,
  zip_code: string,
  phone: string,
  website:string,
  description:string,
  thumbnail: string,
  inserted: string,
  updated: string,
  holes: any[],
  tee_types: Tees[],
  location: any[],
  extras: any[],
  links: any[],
  href: string,
  type: string,
}
